/// <reference types="react" />
export declare function bind(tag: string, block: string, elem: string): any;
export declare function factory(tag: string, block: string, elem: string): any;
import { ReactNode, ReactChild, DOMElement, DOMAttributes, HTMLAttributes, ChangeTargetHTMLAttributes, ClassAttributes } from 'react';
export declare type StrictReactFragment = Array<ReactChild | any[] | boolean>;
export declare type StrictReactNode = ReactChild | StrictReactFragment | boolean | null | undefined;
export interface MarkupProps<E extends HTMLElement, M> extends ClassAttributes<E>, HTMLAttributes<E> {
    mods?: M;
}
export interface ChangeTargetMarkupProps<E extends HTMLElement, M> extends ClassAttributes<E>, ChangeTargetHTMLAttributes<E> {
    mods?: M;
}
export interface DOMMarkupFactory<P, A extends DOMAttributes<E>, E extends Element> {
    (child?: StrictReactNode, ...children: ReactNode[]): DOMElement<A, E>;
    (props?: P, ...children: ReactNode[]): DOMElement<A, E>;
}
export declare type HTMLMarkupFactory<T extends HTMLElement, M> = DOMMarkupFactory<MarkupProps<T, M>, HTMLAttributes<T>, T>;
export declare type ChangeTargetHTMLMarkupFactory<T extends HTMLElement, M> = DOMMarkupFactory<ChangeTargetMarkupProps<T, M>, ChangeTargetHTMLAttributes<T>, T>;
export declare type TagA<M> = HTMLMarkupFactory<HTMLAnchorElement, M>;
export declare type TagABBR<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagADDRESS<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagAREA<M> = HTMLMarkupFactory<HTMLAreaElement, M>;
export declare type TagARTICLE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagASIDE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagAUDIO<M> = HTMLMarkupFactory<HTMLAudioElement, M>;
export declare type TagB<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagBASE<M> = HTMLMarkupFactory<HTMLBaseElement, M>;
export declare type TagBDI<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagBDO<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagBIG<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagBLOCKQUOTE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagBODY<M> = HTMLMarkupFactory<HTMLBodyElement, M>;
export declare type TagBR<M> = HTMLMarkupFactory<HTMLBRElement, M>;
export declare type TagBUTTON<M> = HTMLMarkupFactory<HTMLButtonElement, M>;
export declare type TagCANVAS<M> = HTMLMarkupFactory<HTMLCanvasElement, M>;
export declare type TagCAPTION<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagCITE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagCODE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagCOL<M> = HTMLMarkupFactory<HTMLTableColElement, M>;
export declare type TagCOLGROUP<M> = HTMLMarkupFactory<HTMLTableColElement, M>;
export declare type TagDATA<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDATALIST<M> = HTMLMarkupFactory<HTMLDataListElement, M>;
export declare type TagDD<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDEL<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDETAILS<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDFN<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDIALOG<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagDIV<M> = HTMLMarkupFactory<HTMLDivElement, M>;
export declare type TagDL<M> = HTMLMarkupFactory<HTMLDListElement, M>;
export declare type TagDT<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagEM<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagEMBED<M> = HTMLMarkupFactory<HTMLEmbedElement, M>;
export declare type TagFIELDSET<M> = HTMLMarkupFactory<HTMLFieldSetElement, M>;
export declare type TagFIGCAPTION<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagFIGURE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagFOOTER<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagFORM<M> = HTMLMarkupFactory<HTMLFormElement, M>;
export declare type TagH1<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagH2<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagH3<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagH4<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagH5<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagH6<M> = HTMLMarkupFactory<HTMLHeadingElement, M>;
export declare type TagHEAD<M> = HTMLMarkupFactory<HTMLHeadElement, M>;
export declare type TagHEADER<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagHGROUP<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagHR<M> = HTMLMarkupFactory<HTMLHRElement, M>;
export declare type TagHTML<M> = HTMLMarkupFactory<HTMLHtmlElement, M>;
export declare type TagI<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagIFRAME<M> = HTMLMarkupFactory<HTMLIFrameElement, M>;
export declare type TagIMG<M> = HTMLMarkupFactory<HTMLImageElement, M>;
export declare type TagINPUT<M> = ChangeTargetHTMLMarkupFactory<HTMLInputElement, M>;
export declare type TagINS<M> = HTMLMarkupFactory<HTMLModElement, M>;
export declare type TagKBD<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagKEYGEN<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagLABEL<M> = HTMLMarkupFactory<HTMLLabelElement, M>;
export declare type TagLEGEND<M> = HTMLMarkupFactory<HTMLLegendElement, M>;
export declare type TagLI<M> = HTMLMarkupFactory<HTMLLIElement, M>;
export declare type TagLINK<M> = HTMLMarkupFactory<HTMLLinkElement, M>;
export declare type TagMAIN<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagMAP<M> = HTMLMarkupFactory<HTMLMapElement, M>;
export declare type TagMARK<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagMENU<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagMENUITEM<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagMETA<M> = HTMLMarkupFactory<HTMLMetaElement, M>;
export declare type TagMETER<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagNAV<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagNOSCRIPT<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagOBJECT<M> = HTMLMarkupFactory<HTMLObjectElement, M>;
export declare type TagOL<M> = HTMLMarkupFactory<HTMLOListElement, M>;
export declare type TagOPTGROUP<M> = HTMLMarkupFactory<HTMLOptGroupElement, M>;
export declare type TagOPTION<M> = HTMLMarkupFactory<HTMLOptionElement, M>;
export declare type TagOUTPUT<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagP<M> = HTMLMarkupFactory<HTMLParagraphElement, M>;
export declare type TagPARAM<M> = HTMLMarkupFactory<HTMLParamElement, M>;
export declare type TagPICTURE<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagPRE<M> = HTMLMarkupFactory<HTMLPreElement, M>;
export declare type TagPROGRESS<M> = HTMLMarkupFactory<HTMLProgressElement, M>;
export declare type TagQ<M> = HTMLMarkupFactory<HTMLQuoteElement, M>;
export declare type TagRP<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagRT<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagRUBY<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagS<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSAMP<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSCRIPT<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSECTION<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSELECT<M> = ChangeTargetHTMLMarkupFactory<HTMLSelectElement, M>;
export declare type TagSMALL<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSOURCE<M> = HTMLMarkupFactory<HTMLSourceElement, M>;
export declare type TagSPAN<M> = HTMLMarkupFactory<HTMLSpanElement, M>;
export declare type TagSTRONG<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSTYLE<M> = HTMLMarkupFactory<HTMLStyleElement, M>;
export declare type TagSUB<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSUMMARY<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagSUP<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagTABLE<M> = HTMLMarkupFactory<HTMLTableElement, M>;
export declare type TagTBODY<M> = HTMLMarkupFactory<HTMLTableSectionElement, M>;
export declare type TagTD<M> = HTMLMarkupFactory<HTMLTableDataCellElement, M>;
export declare type TagTEXTAREA<M> = ChangeTargetHTMLMarkupFactory<HTMLTextAreaElement, M>;
export declare type TagTFOOT<M> = HTMLMarkupFactory<HTMLTableSectionElement, M>;
export declare type TagTH<M> = HTMLMarkupFactory<HTMLTableHeaderCellElement, M>;
export declare type TagTHEAD<M> = HTMLMarkupFactory<HTMLTableSectionElement, M>;
export declare type TagTIME<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagTITLE<M> = HTMLMarkupFactory<HTMLTitleElement, M>;
export declare type TagTR<M> = HTMLMarkupFactory<HTMLTableRowElement, M>;
export declare type TagTRACK<M> = HTMLMarkupFactory<HTMLTrackElement, M>;
export declare type TagU<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagUL<M> = HTMLMarkupFactory<HTMLUListElement, M>;
export declare type TagVAR<M> = HTMLMarkupFactory<HTMLElement, M>;
export declare type TagVIDEO<M> = HTMLMarkupFactory<HTMLVideoElement, M>;
export declare type TagWBR<M> = HTMLMarkupFactory<HTMLElement, M>;
